language: node_js

node_js:
    - 13

services:
    - docker

install:
    - echo "nothing needs to be installed"

before_script:
    - echo "no tests"

script:
    - docker --version
    - docker build -t simple-node --build-arg FAVORITE_FOOD=${FAVORITE_FOOD} .
    - docker tag simple-node garcialuiz/simple-node

    
after_success:
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
    - docker push garcialuiz/simple-node